[versions]
baksmali = "3.0.9"
commons_io = "2.21.0"
commons_cli = "1.11.0"
commons_lang3 = "3.20.0"
commons_text = "1.15.0"
dexlib2 = "3.0.9"
guava = "33.5.0-jre"
junit = "4.13.2"
r8 = "9.0.32"
smali = "3.0.9"
xmlpull = "1.1.3.1"
xmlunit = "2.11.0"
maven-publish = "0.36.0"

[libraries]
baksmali = { module = "com.android.tools.smali:smali-baksmali", version.ref = "baksmali" }
commons_cli = { module = "commons-cli:commons-cli", version.ref = "commons_cli"}
commons_io = { module = "commons-io:commons-io", version.ref = "commons_io" }
commons_lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons_lang3" }
commons_text = { module = "org.apache.commons:commons-text", version.ref = "commons_text" }
dexlib2 = { module = "com.android.tools.smali:smali-dexlib2", version.ref = "dexlib2" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit = { module = "junit:junit", version.ref = "junit" }
r8 = { module = "com.android.tools:r8", version.ref = "r8" }
smali = { module = "com.android.tools.smali:smali", version.ref = "smali" }
xmlpull = { module = "xmlpull:xmlpull", version.ref = "xmlpull" }
xmlunit = { module = "org.xmlunit:xmlunit-legacy", version.ref = "xmlunit" }

[plugins]
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
